- _oasis
- lib/semaphore.ml
- lib/semaphore.mli
The semaphore is used in `xcp-networkd` to limit the number of
concurrent executions of a command (CA-225272).
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> add semaphore implementation to stdext

- lib/xapi-stdext/stdext.ml
- xapi-stdext-threads.opam
This PR provides additional fixups and cleanups appeared after new rebuilds after the release of `xapi-stdext 3.0.0`. These have been already included in `xs-opam` as patches and do not require a new release.
A new release will be made once we have ported the libraries dependent on `stdext` to the new structure and the library can be additionally simplified, or earlier if needed for other reasons.
> Port to jbuilder: cleanup and fixup PR

- .travis.yml
- lib/xapi-stdext-encodings/jbuild
- lib_test/jbuild
- lib_test/suite.ml
- lib_test/test_encodings.ml
- xapi-stdext-encodings.opam
This was a quicktest in xapi, but in fact it unit tests Xapi_stdext_encodings, so it belongs here.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
> Move quicktest_encodings from xapi into a unit test

- .travis.yml
- lib/xapi-stdext-unix/unixext.ml
- lib/xapi-stdext-unix/unixext.mli
- lib/xapi-stdext-unix/unixext_open_stubs.c
See discussion in https://ocaml.github.io/ocamlunix/ocamlunix.html#sec118
and xapi-project/xen-api#3570
This also fixed another potential issue in `unixext_open_stubs`
>  really_write: remove deprecation and make robust against EINTR

- lib/xapi-stdext-unix/unixext.ml
- lib/xapi-stdext-unix/unixext.mli
- xapi-stdext-unix.opam
See e.g. https://github.com/ocaml/ocaml/blob/trunk/otherlibs/unix/unix.ml#L328-L332
This PR depends on the release of https://github.com/xapi-project/ocaml-fd-send-recv now that the new interface has been merged
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> unixext: update interface to mimick the ocaml Unix one (fd-send-recv >= 2.0.0)

- .travis.yml
- lib/xapi-stdext-unix/unixext_stubs.c
We rarely see statvfs return 0 for bfree and suspect that this is a GC
related problem. The existing implementation violates rule 6 in the
OCaml manual
https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec442
which mandates to use caml_modify when updating a field with an existing
value. This commit handles this by using Store_field. See also the
discussion at
https://discuss.ocaml.org/t/finding-gc-problems-in-c-bindings/3453/2
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> CA-310525 fix C binding for statvfs

- lib/xapi-stdext-unix/unixext.ml
- lib/xapi-stdext-unix/unixext.mli
Now a temporary permission is set to read and write the temp file and
the final permission the user wants is set just before atomically moving
the file.
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CP-32686: fix atomic creation of write-protected files

- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/dune
- lib_test/test_encodings.ml
- xapi-stdext-date.opam
cb5f60dfc136dadd9a28d30a146f75288566a757 meant that any datetimes which
are parsable by ptime would be emitted containing dashes, but clients
have previously expected datetimes coming from the toolstack to be in
the form YYYYMMDDTHH:mm:ssZ. We fix this by removing dashes when
converting a ptime datetime to a string.
> CA-338243 iso8601.to_string backwards compatibility

- lib/xapi-stdext-date/date.ml
We can use ptime to parse any legacy dates by removing
any dashes before passing to ptime.
> CA-338243 remove legacy variant in iso8601

- .travis.yml
- lib_test/dune
- lib_test/suite.ml
- lib_test/test_encodings.ml
- stdext.opam
- xapi-stdext-encodings.opam
It's the only library that currently has tests
xapi-stdext is ignored in travis now, nothing else is using it and it
can ber dropped from now on.
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> CP-33121: run encodings tests as part of the encodings package

- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/date.mli
- lib/xapi-stdext-date/dune
- lib_test/test_encodings.ml
Allow client to call `Date.localtime ()` and
create a datetime based on the localtime.
> CA-342171 allow clients to create an iso8601 from localtime

- .travis.yml
- lib/xapi-stdext-date/dune
- lib/xapi-stdext-date/test.ml
- lib/xapi-stdext-encodings/dune
- lib/xapi-stdext-encodings/test.ml
- lib_test/dune
- lib_test/test_encodings.ml
- xapi-stdext-date.opam
- xapi-stdext-encodings.opam
The tests of each package have been moved next to the file with code they're testing, to minimize this sort of dependency to reappear in the future.
The alcotest information for encodings has been changed to try to be more informative instead of repeatedly printing "encodings" for all tests.
> CP-33121: remove dependency of date in encodings tests

- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/date.mli
- lib/xapi-stdext-date/dune
- lib_test/test_encodings.ml
Allow client to call `Date.localtime ()` and
create a datetime based on the localtime.
This backport was applied cleanly
> Backport! CA-342171 allow clients to create an iso8601 from localtime

- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/test.ml
The SDK exposes our iso8601 type as an actual iso8601 value, and takes
advantage of iso8601 libraries in other languages. Therefore in order
for the SDK to work as expected, we need to align more closely with
the iso8601 specification. Internally we try our best to coerce the
iso8601 parameters into rfc3339, since rfc3339 is what ptime expects.
One particular error we have seen so far is that our date library rejects
datetime strings without a timezone qualifier (which is fixed by this change).
Signed-off-by: Ben Anson <ben.anson@citrix.com>
> XSI-894 handle iso8601's with no timezone

- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/date.mli
- lib/xapi-stdext-date/test.ml
We must be able to convert all iso8601's to float, in order to avoid
a Java SDK regression
> XSI-894 date.iso8601.to_float should assume UTC

- .ocamlformat
- lib/xapi-stdext-pervasives/pervasiveext.mli
- lib/xapi-stdext-std/dune
- lib/xapi-stdext-std/listext.ml
- lib/xapi-stdext-std/listext.mli
- lib/xapi-stdext-std/listext_test.ml
This deprecates all functions in Listext that are present in Stdlib.List so it's bound to break some builds when integrating it into xs-opam.
Aside from that `sub` doesn't throw errors on invalid indeces, instead returning empty lists for empty ranges.
The used functions of Listext are the set functionality (`setify`, `set_equiv`, `set_difference`, `intersect`, `subset`), `assoc_default`, `replace_assoc`, `update_assoc`, `between` `take` and `chop`.
The set operations I think should be removed by changing the datatypes in xapi. I think the rest are reasonable to use. It seems that most of the listext module is not used and I'm tempted to deprecate the rest functions and remove them sooner rather than later.
> CP-34643: deprecate and test functionality in listext

- lib/xapi-stdext-unix/dune
- xapi-stdext-unix.opam
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
> unix: remove unused stdext-std dependency

- .github/workflows/gh-pages.yml
- README.md
- lib/xapi-stdext-std/dune
- lib/xapi-stdext-std/listext.ml
- lib/xapi-stdext-std/listext.mli
- lib/xapi-stdext-std/listext_test.ml
- lib/xapi-stdext-threads/semaphore.mli
- xapi-stdext-date.opam
- xapi-stdext-encodings.opam
- xapi-stdext-pervasives.opam
- xapi-stdext-std.opam
- xapi-stdext-threads.opam
- xapi-stdext-unix.opam
- xapi-stdext-zerocheck.opam
The deprecation warning from listext have all cleaned up, so removing these is safe.
The docs are published to https://xapi-project.github.io/stdext/ and the resulting List documentation can be read at https://xapi-project.github.io/stdext/xapi-stdext-std/Xapi_stdext_std/Listext/List/index.html  
Opam metadata for all packages was revamped to able to build documentation.
> Drop deprecated functions from Listext, publish docs

- CHANGES.md
- lib/xapi-stdext-date/date.ml
- lib/xapi-stdext-date/date.mli
- lib/xapi-stdext-date/test.ml
Currently the only way to create dates is from floats, since this is quite non-descript semantically, add a new name for these conversion functions, stating that they are meant to be unix timestamps, and allow conversions to and from ptime, which is now the main actual type that implements dates.
There's a new helper function to get the current time in date form as well.
The origin of unix time has been renamed to `epoch`from `never`: having never being equal to is not quite accurate even if in reality the value should be very rare.
In the future the functions with `float` in the name and `never` will be deprecated. not forcing it here allows to have a non-breaking transition path
> Date: allow conversions from ptime.t, and unix time

- dune-project
- lib/xapi-stdext-unix/blkgetsize.h
- lib/xapi-stdext-unix/blkgetsize_stubs.c
- lib/xapi-stdext-unix/unixext_stubs.c
- xapi-stdext-encodings.opam
> CA-382014: Fix blkgetsize return type mismatch

- lib/xapi-stdext-unix/blkgetsize.h
- lib/xapi-stdext-unix/blkgetsize_stubs.c
- lib/xapi-stdext-unix/unixext_stubs.c
* unixext_stubs: fix const warning
* CA-382014: blkgetsize: fix return type mismatch
This code is distributed as part of https://github.com/xapi-project/xs-opam/.
> Backport CA-382014 - type mismatch in stubs

- dune-project
- xapi-stdext-encodings.opam
- xapi-stdext-encodings.opam.template
- xapi-stdext-unix-opam.template
- xapi-stdext-unix.opam
- xapi-stdext-unix.opam.template
The opam files were hand edited, but they are generated from 'dune-project', so running 'dune build' would undo any changes.
Fixes https://github.com/xapi-project/stdext/issues/78 Fixes: 42f237c ("opam: update metadata")
No functional change.
> [maintenance]: fix dune-project

- lib/xapi-stdext-unix/unixext.ml
To reproduce a forkexecd unit test failure I've run it under [rr](https://rr-project.org/). This caused a different failure: EINTR from read.
Unixext already has code to defend against EINTR on write, but not on read: add missing loop.
It is unclear whether this is a bug in `rr` or not, but according to the `signal(7)` manpage some syscalls may return `EINTR` even when `RESTARTSYS` handling is set for the signal, but `read` isn't one of those syscalls:
https://man7.org/linux/man-pages/man7/signal.7.html see "Interruption of system calls and library functions by signal handlers"
And although RESTARTSYS seems to be the default handling for signals, if you establish a custom handler for *any* signal in OCaml I think you may always risk getting `EINTR`, because the `sigaction` call in OCaml …
> CA-387588: Unixext.really_read: restart on EINTR
